version: '3'
services:
  db:
    image: postgres:10
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dbapp

  nodeapp:
    build:
      context: .
    links:
      - db
    ports:
      - 3002:3000
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=dbapp
